# Configuración para GitHub Secret Scanning
# Este archivo ayuda a configurar el escaneo de secretos

# Excluir directorios de dependencias de terceros
exclude-paths:
  - 'node_modules/**'
  - '**/node_modules/**'
  - 'mobile-app/node_modules/**'
  - 'apps/worker-mobile/node_modules/**'
  - '**/node_modules/@react-native/debugger-frontend/**'
  - '**/node_modules/@react-native/community-cli-plugin/**'

# Patrones de secretos que deben ser ignorados (falsos positivos)
# Estos son ejemplos de patrones que pueden aparecer en documentación o tests
secret-scanning:
  # Ignorar patrones en archivos de documentación
  - pattern: 'AIzaSy[A-Za-z0-9_-]{35}'
    paths:
      - '*.md'
      - 'docs/**'
      - 'README.md'

  # Ignorar patrones en archivos de configuración de ejemplo
  - pattern: 'your_google_maps_api_key'
    paths:
      - '*.md'
      - 'docs/**'
      - 'examples/**'

  # Ignorar patrones en archivos de test
  - pattern: 'test_key|example_key|placeholder_key'
    paths:
      - '**/*.test.*'
      - '**/*.spec.*'
      - 'tests/**'

  # Ignorar variables de entorno de ejemplo
  - pattern: 'NEXT_PUBLIC_.*_EXAMPLE|SUPABASE_.*_EXAMPLE'
    paths:
      - '*.md'
      - 'docs/**'
      - 'examples/**'

  # Ignorar clave API de React Native Debugger (dependencia de terceros)
  - pattern: 'AIzaSyCCSOx25vrb5z0tbedCB3_JRzzbVW6Uwgw'
    paths:
      - '**/node_modules/@react-native/debugger-frontend/**'
      - '**/node_modules/@react-native/community-cli-plugin/**'
      - 'mobile-app/node_modules/**'
      - 'apps/worker-mobile/node_modules/**'
    reason: 'Third-party dependency key in React Native Debugger'

  # Ignorar clave API de Google Maps revocada (breach resuelto)
  - pattern: 'AIzaSyDJO-K651Oj7Pkh_rVHGw0hmPb7NtQCozQ'
    paths:
      - '**'
    reason: 'Revoked Google Maps API key - breach resolved, files removed'

# Configuración de alertas
alerts:
  # Habilitar alertas para secretos reales
  enabled: true

  # Configurar notificaciones
  notifications:
    email: true
    webhook: false

# Configuración de validación
validation:
  # Validar secretos antes de crear alertas
  enabled: true

  # Patrones de validación personalizados
  custom-patterns:
    - name: 'Google Maps API Key'
      pattern: 'AIzaSy[A-Za-z0-9_-]{35}'
      severity: 'high'

    - name: 'Supabase Service Role Key'
      pattern: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"
      severity: 'critical'

    - name: 'GitHub Personal Access Token'
      pattern: 'ghp_[A-Za-z0-9]{36}'
      severity: 'high'
