# Patrones para GitHub Secret Scanning
# Configuración para ignorar falsos positivos en documentación

# Patrones que deben ser ignorados en archivos de documentación
ignore-patterns:
  # Google Maps API Key en documentación
  - name: 'Google Maps API Key in docs'
    pattern: 'AIzaSy[A-Za-z0-9_-]{35}'
    paths:
      - '*.md'
      - 'docs/**'
      - 'README.md'
      - 'GOOGLE-MAPS-*.md'

  # Clave específica de React Native Debugger (dependencia de terceros)
  - name: 'React Native Debugger API Key'
    pattern: 'AIzaSyCCSOx25vrb5z0tbedCB3_JRzzbVW6Uwgw'
    paths:
      - '**/node_modules/@react-native/debugger-frontend/**'
      - '**/node_modules/@react-native/community-cli-plugin/**'
      - 'mobile-app/node_modules/**'
      - 'apps/worker-mobile/node_modules/**'

  # Clave específica de Google Maps revocada
  - name: 'Revoked Google Maps API Key'
    pattern: 'AIzaSyDJO-K651Oj7Pkh_rVHGw0hmPb7NtQCozQ'
    paths:
      - '**'

  # Patrones de ejemplo en documentación
  - name: 'Example patterns in docs'
    pattern: 'your_.*_key|example_.*_key|placeholder_.*_key'
    paths:
      - '*.md'
      - 'docs/**'
      - 'examples/**'

  # Variables de entorno de ejemplo
  - name: 'Example environment variables'
    pattern: 'NEXT_PUBLIC_.*_EXAMPLE|SUPABASE_.*_EXAMPLE'
    paths:
      - '*.md'
      - 'docs/**'
      - 'examples/**'

  # Patrones en archivos de configuración de ejemplo
  - name: 'Example config patterns'
    pattern: 'test_key|demo_key|sample_key'
    paths:
      - '*.md'
      - 'docs/**'
      - 'examples/**'
      - '*.example.*'
      - '*.sample.*'

# Configuración de severidad
severity-levels:
  # Secretos críticos (tokens de servicio, claves privadas)
  critical:
    - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+" # JWT tokens
    - 'sk_[A-Za-z0-9]{48}' # Stripe secret keys
    - 'pk_[A-Za-z0-9]{48}' # Stripe publishable keys

  # Secretos de alta severidad (API keys, tokens de acceso)
  high:
    - 'AIzaSy[A-Za-z0-9_-]{35}' # Google API keys
    - 'ghp_[A-Za-z0-9]{36}' # GitHub personal access tokens
    - 'gho_[A-Za-z0-9]{36}' # GitHub OAuth tokens
    - 'ghu_[A-Za-z0-9]{36}' # GitHub user-to-server tokens
    - 'ghs_[A-Za-z0-9]{36}' # GitHub server-to-server tokens
    - 'ghr_[A-Za-z0-9]{36}' # GitHub refresh tokens

  # Secretos de media severidad (claves de desarrollo)
  medium:
    - 'AKIA[A-Z0-9]{16}' # AWS access keys
    - "ya29\\.[A-Za-z0-9_-]+" # Google OAuth tokens
    - '1//[A-Za-z0-9_-]+' # Google OAuth refresh tokens

# Configuración de notificaciones
notifications:
  # Habilitar notificaciones por email
  email: true

  # Habilitar notificaciones en GitHub
  github: true

  # Configurar webhooks (opcional)
  webhook: false
